Global:
  debug: false
  use_gpu: false
  epoch_num: 10
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/vin_rec_finetune
  save_epoch_step: 5
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: ./inference/vin_rec
  use_visualdl: true
  visualdl_log_dir: ./output/vdl_logs
  infer_img: null
  character_dict_path: ./configs/vin_dict.txt
  max_text_length: 17
  infer_mode: false
  use_space_char: false
  distributed: false
  save_res_path: ./output/rec_results.txt
  use_amp: false

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0015  # Reduced learning rate for better convergence
    warmup_epoch: 0  # Disable warmup causing low LR
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: Rosetta  # CNN+RNN compatible with CrossEntropyLoss
  Transform: null
  Backbone:
    name: ResNet34_vd
  Neck:
    name: SequenceEncoder
    hidden_size: 256
  Head:
    name: MultiHead
    head_list:
      - SARHead:
          fc_decay: 0.00001
Loss:
  name: CrossEntropyLoss  # Matches high-performance model training

PostProcess:
  name: SARLabelDecode  # For CrossEntropyLoss
  character_dict_path: ./configs/vin_dict.txt
  use_space_char: false

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: true

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./finetune_data/
    label_file_list:
      - ./finetune_data/train_labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecAug:
      - MultiLabelEncode:
          max_text_length: 17
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - RandomRotate:
          max_angle: 5  # More rotation
      - RandomDistort:
          max_ratio: 0.8  # More distortion
      - RandomContrast:
          contrast_range: [0.8, 1.2]  # Add contrast variation
      - KeepKeys:
          keep_keys:
            - image
            - label      # CTC uses single label
            - length
            - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: true
    num_workers: 0
    use_shared_memory: false

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./finetune_data/
    label_file_list:
      - ./finetune_data/val_labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          max_text_length: 17
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label      # CTC uses single label
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 16
    num_workers: 0
    use_shared_memory: false

Test:
  dataset:
    name: SimpleDataSet
    data_dir: ./finetune_data/
    label_file_list:
      - ./finetune_data/test_labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          max_text_length: 17
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label      # CTC uses single label
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 16
    num_workers: 0
    use_shared_memory: false
